### ISSUE TITLE
[Bug]: CUDA annotation does not match with the Accelerator

### ISSUE THREAD

**Issue by FedeAlonso** [opendatahub-io/opendatahub-community#108]
### ODH Component

ODH Operator

### Current Behavior

When choosing the CUDA Notebook Image when creating a new Workbench, the NVIDIA Accelerators does not get recommended
![Screenshot from 2023-09-13 17-05-51](https://github.com/opendatahub-io/opendatahub-community/assets/31654558/0353f874-65d5-4d2e-834c-f46398fc67d3)

### Expected Behavior

The 'Compatible with image' recommendation should be shown
![Screenshot from 2023-09-13 17-52-31](https://github.com/opendatahub-io/opendatahub-community/assets/31654558/ea61025f-95e1-4c3f-906d-b403f56ef0fb)

### Steps To Reproduce

You must have some AcceleratorProfile installed in the RHODS instance (like the ones [here](https://github.com/rh-aiservices-bu/accelerator-profiles-testing#adding-a-couple-nvidia-examples-too))
1. Log in in RHODS
2. Create a Data Science Project
3. Navigate to that new project inside 'Data Science Projects'
4. Click on 'Create workbench' button
5. In the 'Image selection' dropdown  (in the 'Notebook image' section) chose 'CUDA' 
6. In the 'Accelerator' dropdown  (in the 'Deployment size' section) there are no recommendations/

### Anything else

The CUDA, Pytorch and Tensorflow images come with RHODS by default, and they would probably need to be updated so they have the 'nvidia.com/gpu' compatible annotation.

**Comment by harshad16** [comment]
@FedeAlonso  Which version of RHODS are you using?

**Comment by andrewballantyne** [comment]
How did you install this? There is definitely information need to go along with it. In ODH 1.9 we released Habana, but it has some issues. So we are still investigating the solution and will be releasing this Friday with another update to hopefully help out things.

But OOTB Images are needing to be configured to use the annotation -- and that I don't believe is fully done.

**Comment by harshad16** [comment]
From the OOTB images perspective, the annotations are already in v1.9 
https://github.com/opendatahub-io/odh-manifests/commit/53852c4c620f5ed3cfc77c1d919c523b730ff80e

**Comment by FedeAlonso** [comment]
> @FedeAlonso Which version of ODH/RHODS are you using?

@harshad16  RHODS 4.33 (in a stage environment)

**Comment by FedeAlonso** [comment]
> How did you install this? There is definitely information need to go along with it. In ODH 1.9 we released Habana, but it has some issues. So we are still investigating the solution and will be releasing this Friday with another update to hopefully help out things.
> 
> But OOTB Images are needing to be configured to use the annotation -- and that I don't believe is fully done.

@andrewballantyne I used a QE Pipeline to install the cluster, and then followed @erwangranger instrutions to install the 1.33 Habana version

**Comment by andrewballantyne** [comment]
Ah, that would be likely the problem -- we didn't collect those annotations. Do we need to get those for Intel? Your instructions hopefully are good enough. This is all scuffed because it's not a real release, not ODH, not RHODS. So you're going to get flows that just don't equate to a full feature.

If you install the build from ODH Nightlies you might have better success -- that's our "latest and greatest" of changes.

I'm going to close this as I don't see this as a bug, so much as an unsupported install flow.
