### ISSUE TITLE
ODH Community Governance

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/opendatahub-community#11]
- [x] Code of Conduct
- [x] Update Contributing Guide
- [x] Establish Steering Committee
- [x] Establish Special Interest Groups
- [x] Establish rules for Working Groups

**Comment by shgriffi** [comment]
I've picked up this task and am working through these items.  I should have content ready for review in the next couple of days.

**Comment by shgriffi** [comment]
Associated pull request is [here](https://github.com/opendatahub-io/opendatahub-community/pull/14).

**Comment by LaVLaS** [comment]
Closing this since it was completed in #14
