### ISSUE TITLE
[Bug]: If you delete the NS from the Istio SMMR manually, the model controller doesn't reconcile it

### ISSUE THREAD

**Issue by tarukumar** [opendatahub-io/opendatahub-community#125]
### ODH Component

Model Serving

### Current Behavior

If you delete the NS from the Istio SMMR manually, the model controller doesn't reconcile it

### Expected Behavior

If you delete the NS from the Istio SMMR manually, then model controller should reconcile it and add it to SMMR

### Steps To Reproduce

1. create a namespace or project "my-namespace"
2. deploy an InferenceService
3. wait for kserve pod in "my-namespace" to be up and running
4. remove namepsace from istio smmr
5. check SMMR and obseved that namespace is missing and model controller doesn't reconcile it

### Workaround (if any)

manually add the namespace to smmr

### What browsers are you seeing the problem on? (If applicable)

Chrome

### Open Data Hub Version

```yml
ODH: 2.2.1
RHODS: 1.32,1.33,1.34
```

### Anything else

I verified with the image provide by Vaibhav and it looks like the  issue is fixed with provided image.

`[quay.io/opendatahub/odh-model-controller:fast](http://quay.io/opendatahub/odh-model-controller:fast)`

**Comment by vaibhavjainwiz** [comment]
This issue has been fixed with https://github.com/opendatahub-io/odh-model-controller/pull/84
