### ISSUE TITLE
TrustyAI feature tracker

### ISSUE THREAD

**Issue by ruivieira** [opendatahub-io/opendatahub-community#135]
### TrustyAI service

- https://github.com/trustyai-explainability/trustyai-explainability/issues/416
- https://github.com/trustyai-explainability/trustyai-explainability/issues/151
- https://github.com/trustyai-explainability/trustyai-explainability/issues/150

### TrustyAI operator

- https://github.com/trustyai-explainability/trustyai-service-operator/issues/44
- https://github.com/trustyai-explainability/trustyai-service-operator/issues/99
- https://github.com/trustyai-explainability/trustyai-service-operator/issues/122

**Comment by zdtsw** [comment]
should we have this closed?

**Comment by ruivieira** [comment]
@zdtsw I think so :)
