### ISSUE TITLE
[Bug]: Downloading as a PDF not working

### ISSUE THREAD

**Issue by cdolfi** [opendatahub-io/opendatahub-community#141]
### ODH Component

ODH Notebook Controller

### Current Behavior

When trying to download a notebook as a pdf i get this error
![Screenshot 2023-11-20 at 12 16 58 PM](https://github.com/opendatahub-io/opendatahub-community/assets/47504866/2a83187f-fa89-4fda-a290-e2345801d8fc)

### Expected Behavior

A PDF download of a notebook

### Steps To Reproduce

1. open notebook 
2. click file- save and export notebook as - PDF 

### Workaround (if any)

none 

### What browsers are you seeing the problem on? (If applicable)

Chrome

**Comment by jstourac** [comment]
@cdolfi your original issue has been transferred here already https://github.com/opendatahub-io/notebooks/issues/210 and will be scheduled per the priorities. No need to create the issue here again.
