### ISSUE TITLE
ODH 2.17 Tracker

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-community#157]
Links to tracker issues for components planning updates in this.  Please update you manifests before **August 23rd**. 

Release Date: **August 26th** (Delayed to August 28th)

### Comment Template for automation
```
#Release#
- component_name|release-branch|release-notes
```

**List of component_name:**

- [x] modelregistry
- [x] notebook-controller
- [x] notebooks
- [x] codeflare
- [x] ray
- [x] kueue
- [x] trainingoperator
- [x] trustyai
- [x] odh-dashboard
- [x] data-science-pipelines-operator
- [x] model-mesh
- [x] kserve
- [x] model-mesh-serving
- [x] odh-model-controller

**Comment by sutaakar** [comment]
#Release#
- codeflare | https://github.com/opendatahub-io/codeflare-operator/tree/v1.5.0-odh | https://github.com/opendatahub-io/codeflare-operator/releases/tag/v1.5.0-odh
- ray | https://github.com/opendatahub-io/kuberay/tree/v1.1.2-odh | https://github.com/opendatahub-io/kuberay/releases/tag/v1.1.2-odh
- kueue | https://github.com/opendatahub-io/kueue/tree/v0.7.0-odh-test | https://github.com/opendatahub-io/kueue/releases/tag/v0.7.0-odh-test
- trainingoperator | https://github.com/opendatahub-io/training-operator/tree/v1.8.0-odh | https://github.com/opendatahub-io/training-operator/releases/tag/v1.8.0-odh

**Comment by ChristianZaccaria** [comment]
#Release#
- codeflare|https://github.com/opendatahub-io/codeflare-operator/tree/v1.7.0-odh|https://github.com/opendatahub-io/codeflare-operator/releases/tag/v1.7.0-odh
- kueue|https://github.com/opendatahub-io/kueue/tree/v0.7.0-odh-1|https://github.com/opendatahub-io/kueue/releases/tag/v0.7.0-odh-1
- ray|https://github.com/opendatahub-io/kuberay/tree/v1.1.1-08-14-2024|https://github.com/opendatahub-io/kuberay/releases/tag/v1.1.1-08-14-2024
- trainingoperator|https://github.com/opendatahub-io/training-operator/tree/v1.8.0-odh-1|https://github.com/opendatahub-io/training-operator/releases/tag/v1.8.0-odh-1

**Comment by ChristianZaccaria** [comment]
Hi @AjayJagan, I've noticed that you've [tested the release template](https://github.com/AjayJagan/notes-operator/issues/2) for automation. I just wanted to check with you if the horizontal line between the two links is expected to not have a space.

The template has no spaces, but this causes both links to be mixed together into one, is this expected? Please see my comment above and the edited version. Let me know if I should revert to no spaces, thanks! :)

**Comment by AjayJagan** [comment]
> Hi @AjayJagan, I've noticed that you've [tested the release template](https://github.com/AjayJagan/notes-operator/issues/2) for automation. I just wanted to check with you if the horizontal line between the two links is expected to not have a space.
> 
> The template has no spaces, but this causes both links to be mixed together into one, is this expected? Please see my comment above and the edited version. Let me know if I should revert to no spaces, thanks! :)

Hi @ChristianZaccaria , The automation supports adding spaces in between the `|` so the one that is mentioned above is perfect :)

**Comment by HumairAK** [comment]
#Release#
-  data-science-pipelines-operator | https://github.com/opendatahub-io/data-science-pipelines-operator/tree/v2.5.x | https://github.com/opendatahub-io/data-science-pipelines-operator/releases/tag/v2.5.0

**Comment by dhirajsb** [comment]
MR operator has some open PRs that we hope to close this week/weekend. Is it ok if we do a release by Monday end of day and update the manifests at that time?

**Comment by tarilabs** [comment]
#Release#

modelregistry | https://github.com/opendatahub-io/model-registry-operator/tree/release/v0.2.5 | https://github.com/opendatahub-io/model-registry-operator/releases/tag/v0.2.5

**Comment by harshad16** [comment]
#Release#

- notebooks| [https://github.com/opendatahub-io/notebooks/tree/v1.21.0](https://github.com/opendatahub-io/notebooks/tree/v1.21.0) | [https://github.com/opendatahub-io/notebooks/releases/tag/v1.21.0](https://github.com/opendatahub-io/notebooks/releases/tag/v1.21.0)
- notebook-controller| [https://github.com/opendatahub-io/kubeflow/tree/v1.7.0-15](https://github.com/opendatahub-io/kubeflow/tree/v1.7.0-15) | [https://github.com/opendatahub-io/kubeflow/releases/tag/v1.7.0-15](https://github.com/opendatahub-io/kubeflow/releases/tag/v1.7.0-15)

**Comment by spolti** [comment]
#Release#

- component | branch | tag |
- modelmesh |  https://github.com/opendatahub-io/modelmesh/tree/release-0.12.0-rc0 | https://github.com/opendatahub-io/modelmesh/releases/tag/v0.12.0.4-rc0
- model-mesh-serving | https://github.com/opendatahub-io/modelmesh-serving/tree/release-0.12.0-rc0 | https://github.com/opendatahub-io/modelmesh-serving/releases/tag/v0.12.0.4-rc0
- kserve | https://github.com/opendatahub-io/kserve/tree/release-v0.12.1  | https://github.com/opendatahub-io/kserve/releases/tag/v0.12.1.5
- odh-model-controller | https://github.com/opendatahub-io/odh-model-controller/tree/release-0.12.0 | https://github.com/opendatahub-io/odh-model-controller/releases/tag/v0.12.0.5

**Comment by manaswinidas** [comment]
#Release#

- odh-dashboard | https://github.com/opendatahub-io/odh-dashboard/tree/v2.25.2-odh | https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.25.2-odh

**Comment by ruivieira** [comment]
#Release#
- trustyai|https://github.com/trustyai-explainability/trustyai-service-operator/tree/release/1.25.0|https://github.com/trustyai-explainability/trustyai-service-operator/releases/tag/v1.25.0

**Comment by VaishnaviHire** [comment]
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/5051
