### ISSUE TITLE
ODH 2.18.2 Release Tracker

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/opendatahub-community#160]
Links to tracker issues for components planning updates in this.  Please update you manifests before 

Release Date: 

### Comment Template for automation
```
#Release#
- component_name|release-branch/release-tag|release-notes
```

**List of component_name:**

- [x] modelregistry
- [x] notebook-controller
- [x] notebooks
- [x] codeflare
- [x] ray
- [x] kueue
- [x] trainingoperator
- [x] trustyai
- [x] odh-dashboard
- [x] data-science-pipelines-operator
- [x] model-mesh
- [x] kserve
- [x] model-mesh-serving
- [x] odh-model-controller

**Comment by tarilabs** [comment]
- upstream MR: https://github.com/kubeflow/model-registry/releases/tag/v0.2.7-alpha
- midstream MR: https://github.com/opendatahub-io/model-registry/releases/tag/v0.2.7
- MR Python client: https://pypi.org/project/model-registry/0.2.7a1/
- Model Registry Operator: https://github.com/opendatahub-io/model-registry-operator/releases/tag/v0.2.7

#Release#

modelregistry | https://github.com/opendatahub-io/model-registry-operator/tree/release/v0.2.7 | https://github.com/opendatahub-io/model-registry-operator/releases/tag/v0.2.7

**Comment by mturley** [comment]
#Release#
- odh-dashboard | https://github.com/opendatahub-io/odh-dashboard/tree/v2.26.2-odh-release | https://github.com/opendatahub-io/odh-dashboard/releases/tag/v2.26.2-odh

**Comment by VaishnaviHire** [comment]
#Release#

- codeflare|https://github.com/opendatahub-io/codeflare-operator/tree/v1.8.0-odh | https://github.com/opendatahub-io/codeflare-operator/releases/tag/v1.8.0-odh
- ray|https://github.com/opendatahub-io/kuberay/tree/v1.1.1-08-14-2024 | https://github.com/opendatahub-io/kuberay/releases/tag/v1.1.1-08-14-2024
- kueue|https://github.com/opendatahub-io/kueue/tree/v0.7.0-odh-1 | https://github.com/opendatahub-io/kueue/releases/tag/v0.7.0-odh-1
- trainingoperator|https://github.com/opendatahub-io/training-operator/tree/v1.8.0-odh-1 | https://github.com/opendatahub-io/training-operator/releases/tag/v1.8.0-odh-1

**Comment by VaishnaviHire** [comment]
#Release#

- notebooks| https://github.com/opendatahub-io/notebooks/tree/v1.22.0 | https://github.com/opendatahub-io/notebooks/releases/tag/v1.22.0
- notebook-controller| https://github.com/opendatahub-io/kubeflow/tree/v1.7.0-15 | https://github.com/opendatahub-io/kubeflow/releases/tag/v1.7.0-15

**Comment by VaishnaviHire** [comment]
#Release#

- Kserve | https://github.com/opendatahub-io/kserve/tree/v0.12.1.6 | https://github.com/opendatahub-io/kserve/releases/tag/v0.12.1.6
- Model Mesh | https://github.com/opendatahub-io/modelmesh-serving/tree/v0.12.0.5-rc0 | https://github.com/opendatahub-io/modelmesh-serving/releases/tag/v0.12.0.5-rc0
- ODH Model Controller | https://github.com/opendatahub-io/odh-model-controller/tree/v0.12.0.6 | https://github.com/opendatahub-io/odh-model-controller/releases/tag/v0.12.0.6

**Comment by VaishnaviHire** [comment]
#Release#

data-science-pipelines-operator | https://github.com/opendatahub-io/data-science-pipelines-operator/tree/v2.5.x | https://github.com/opendatahub-io/data-science-pipelines-operator/releases/tag/v2.5.0

**Comment by VaishnaviHire** [comment]
#Release#

trustyai | https://github.com/trustyai-explainability/trustyai-service-operator/tree/release/1.26.0 | https://github.com/trustyai-explainability/trustyai-service-operator/releases/tag/v1.26.0

**Comment by VaishnaviHire** [comment]
https://github.com/redhat-openshift-ecosystem/community-operators-prod/pull/5228
