### ISSUE TITLE
[Bug]: Cannot create Model Registry

### ISSUE THREAD

**Issue by tomaszgaska-europe** [opendatahub-io/opendatahub-community#164]
### ODH Component

Model Serving

### Current Behavior

When trying to create registry error appears:

admission webhook "vmodelregistry.opendatahub.io" denied the request: ModelRegistry.modelregistry.opendatahub.io "test" is invalid: [spec.istio.gateway.rest.tls.credentialName: Required value: missing rest credentialName and operator environment variable DEFAULT_CERT, spec.istio.gateway.grpc.tls.credentialName: Required value: missing grpc credentialName and operator environment variable DEFAULT_CERT]

DEFAULT_CERT value in registry configmap is empty

### Expected Behavior

Model Registry

### Steps To Reproduce

1. This is quite fresh installation started from 2.20
2. Everything else seems to work fine
3. This was the first try to create model registry

### Workaround (if any)

Havent found

### What browsers are you seeing the problem on? (If applicable)

Firefox, Chrome, Safari, Microsoft Edge

### Open Data Hub Version

```yml
2.22
```

**Comment by tarilabs** [comment]
looks to me this was solved by

- https://github.com/opendatahub-io/opendatahub-operator/pull/1457

cc @Al-Pragliola
