### ISSUE TITLE
[Bug]: Cannot create model regitsry

### ISSUE THREAD

**Issue by madiTG** [opendatahub-io/opendatahub-community#165]
### ODH Component

Model Serving

### Current Behavior

When try to create model registry i get error like this:

admission webhook "[vmodelregistry.opendatahub.io](http://vmodelregistry.opendatahub.io/)" denied the request: [ModelRegistry.modelregistry.opendatahub.io](http://modelregistry.modelregistry.opendatahub.io/) "test" is invalid: [spec.istio.gateway.rest.tls.credentialName: Required value: missing rest credentialName and operator environment variable DEFAULT_CERT, spec.istio.gateway.grpc.tls.credentialName: Required value: missing grpc credentialName and operator environment variable DEFAULT_CERT]

DEFAULT_CERT is indeed empty

### Expected Behavior

Registry is being created

### Steps To Reproduce

1. This is quite fresh installation started from 2.20

2. Everything else seems to work fine

3. This was the first try to create model registry

### Workaround (if any)

Haven't found

### Open Data Hub Version

```yml
2.22
```

**Comment by Al-Pragliola** [comment]
> looks to me this was addressed by
> 
>     -  [fix: bug not filling params.env with default cert value in model registry operator opendatahub-operator#1457](https://github.com/opendatahub-io/opendatahub-operator/pull/1457)
> 
> 
> cc @Al-Pragliola

Yes, indeed, a possible temporary workaround until the fix makes its way into a new release is to run these commands:

```shell
oc exec $(oc get pod -n openshift-operators -o custom-columns=":metadata.name" | grep opendatahub-operator)  -n openshift-operators -- bash -c 'sed -i "s/^DEFAULT_CERT=.*/DEFAULT_CERT=default-modelregistry-cert/" /opt/manifests/model-registry-operator/overlays/odh/params.env'
oc patch datasciencecluster default-dsc --type='json' -p='[{"op": "replace", "path": "/spec/components/modelregistry/managementState", "value": "Removed"}]'
# wait for the operator to remove the resources
oc patch datasciencecluster default-dsc --type='json' -p='[{"op": "replace", "path": "/spec/components/modelregistry/managementState", "value": "Managed"}]'
```

keep in mind that you will lose the changes made to the opendatahub-operator on a pod restart/reschedule

**Comment by madiTG** [comment]
Workaround is working fine.

**Comment by tarilabs** [comment]
Closing on original poster confirmation in https://github.com/opendatahub-io/opendatahub-community/issues/165#issuecomment-2558517999
