### ISSUE TITLE
Add repository templates for projects, SIGs and WGs

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/opendatahub-community#19]
To standardize the minimum requirements for all git repos in the opendatahub-io org, we need to create repo templates for any new repos that will be initialized in the github.com/opendatahub-io organization

Template List:
- [ ] New projects starting from scratch
- [ ] Special Interest Groups
- [ ] Working Groups

I would assume the base requirements would be to have a
- [ ] Software License
- [ ] README template
- [ ] Standard templates bug reports and feature requests
- [ ] OWNERS file

GitHub Project Template [Documentation](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository)

**Comment by atheo89** [comment]
The pull request is under review: https://github.com/opendatahub-io/odh-template-sig/pull/1
