### ISSUE TITLE
Need to join slack for ODH

### ISSUE THREAD

**Issue by arpitsharma-hexad** [opendatahub-io/opendatahub-community#26]
Hello Team,
I want to join odh slack workspace. It says "Contact the workspace administrator at Open Data Hub for an invitation".Can anybody invite my email id "arpitvipulsharma@gmail.com"
Thanks

**Comment by LaVLaS** [comment]
@arpitsharma-hexad You can use this Slack invite link to join [odh-io](https://join.slack.com/t/odh-io/shared_invite/zt-13hp18gxj-Yb34PfQyP9GDmKMU7AkVYw)

**Comment by shgriffi** [comment]
Closing this out given the link should allow @arpitsharma-hexad to join.
