### ISSUE TITLE
Slack invites expired?

### ISSUE THREAD

**Issue by aslom** [opendatahub-io/opendatahub-community#30]
Clicking link in "[Slack](https://join.slack.com/t/odh-io/shared_invite/zt-18ptx7far-SWO4jkDbuA7Sq8Mut3JbcA) on channel #sig-platform" from https://github.com/opendatahub-io/opendatahub-community/tree/master/sig-platform

shows 

"This link is no longer active

To join this workspace, you’ll need to ask the person who originally invited you for a new link."

**Comment by aslom** [comment]
BTW: where do I find instructions how to join [odh-io.slack.com](https://odh-io.slack.com/) and Open Data Hub mailing list [odh-community@googlegroups.com](mailto:odh-community@googlegroups.com) ? They are mentioned in main github page https://github.com/opendatahub-io/opendatahub-community but no links how to join?

**Comment by accorvin** [comment]
@aslom given that our ODH slack is a free plan I believe we have to periodically generate new invite links. [Here](https://join.slack.com/t/odh-io/shared_invite/zt-1qi61vhxi-Fyx5jLjO3OKx~hBg8c6mmQ) is an updated one.

I believe you can join the mailing list using [this link](https://lists.opendatahub.io/admin/lists/). See [this page](https://opendatahub.io/community.html) for some more odh community items.

**Comment by LaVLaS** [comment]
Thx for the assist Alex.  All references to the new slack invitation has been updated in the repo
