### ISSUE TITLE
Intel Habana model training support

### ISSUE THREAD

**Issue by andrewballantyne** [opendatahub-io/opendatahub-community#41]
This is a tracker for all the various bits we will need to track to complete the feature work to add Habana Accelerator support.

# Requirements

Karl testing edit, will link or paste requirements soon

# Individual Efforts

* UX: https://github.com/opendatahub-io/sig-ml-developer-experience/issues/32
    * Lead: @yannnz
* UI: https://github.com/opendatahub-io/odh-dashboard/issues/1450
    * Lead: @Gkrumbach07 
* Dev - Notebook: https://github.com/opendatahub-io/notebooks/issues/96
    * Lead: @harshad16 
* QE: (add link)
    * Lead: @nehachopra27
* Doc: (add link)
    * Lead: TBD

**Comment by jkoehler-redhat** [comment]
@lucferbux was this included in ODH 1.9 release?  I do not see it in the release notes.

**Comment by lucferbux** [comment]
> @lucferbux was this included in ODH 1.9 release? I do not see it in the release notes.

Yes, this is included and it's ready in incubation, we need to reflect that in the release notes.

**Comment by andrewballantyne** [comment]
Dashboard effort is now merged into `main` and heading towards 1.34 RHODS. I'll leave this open as @harshad16 works his way through the image testing.

**Comment by harshad16** [comment]
This was completed with RHODS 1.34 
Habana based changes from both Workbenches and Dashboard are in that release.
/close
