### ISSUE TITLE
Support FM Prompt tuning using Codeflare/Distributed Workloads

### ISSUE THREAD

**Issue by jkoehler-redhat** [opendatahub-io/opendatahub-community#47]
This is a tracker for all the various bits we will need to track to complete the feature work to add Prompt tuning for FM models.

# Requirements

Add requirements

# Individual Efforts

* UX: (add link)
    * Lead: TBD
* UI: (add link)
    * Lead: TBD
* Dev: (add link)
    * Lead: TBD
* QE: (add link)
    * Lead: TBD
* Doc: (add link)
    * Lead: TBD

**Comment by accorvin** [comment]
This is complete in odh
